{-
euler 2
-------

Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.

-}


fiblistWhile cond list 
      |length list > 1 && (cond $ last list) 
        = fiblistWhile cond (list ++ [((head $ last2 list) + (last $ last2 list))])
      |otherwise  = take ((length list) - 1) list
  where last2 list = drop (length list - 2) list
  
iseven x = mod x 2 == 0 


solution :: Integer
solution = sum $ filter iseven $ fiblistWhile (<=4000000) [1,2]




