{-
euler 45
-------


Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle 	  	Tn=n(n+1)/2 	  	1, 3,  6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  1, 5, 12, 22, 35, ...  
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.



-}
{-
a(a+1)/2 = b(3b-1)/2 = c(2c-1) 
a^2/2 + a/2 = 3b^2/2 - b/2 = 2c^2 - c 
-}
import Data.List

import Math

next cand@(a,b,c) = if (t == p) then 
                      if (p == h) then (True,cand)
                      else if (p < h) then (False,(a,b+1,c)) else (False,(a,b,c+1))
                    else   if (t > p) then (False,(a,b+1,c)) else (False,(a+1,b,c))
    where t = polygonalNum 3 a
          p = polygonalNum 5 b
          h = polygonalNum 6 c
          
takeNext cand@(True,_) = cand
takeNext cand@(False,triplet) = takeNext $ next triplet

printSol (_,(a,b,c)) = (show $ polygonalNum 3 a)++" = T"++show a++" = P"++show b++" = H"++ show c 

solution = printSol $ takeNext (False,(286,165,143))


  
